In [1]:
import pandas as pd

In [2]:
print("Hello World!")

Hello World!

In [3]:
!pip install nba_api

Requirement already satisfied: nba_api in /usr/local/lib/python3.10/dist-packages (1.4.1)
Requirement already satisfied: certifi<2024.0.0,>=2023.7.22 in /usr/local/lib/python3.10/dist-packages (from nba_api) (2023.11.17)
Requirement already satisfied: numpy<2.0.0,>=1.22.2 in /usr/local/lib/python3.10/dist-packages (from nba_api) (1.25.2)
Requirement already satisfied: requests<3.0,>=2.31 in /usr/local/lib/python3.10/dist-packages (from nba_api) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0,>=2.31->nba_api) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0,>=2.31->nba_api) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0,>=2.31->nba_api) (2.0.7)

In [9]:
from nba_api.stats.static import players

# get_players returns a list of dictionaries, each representing a player.
nba_players = players.get_players()
print("Number of players fetched: {}".format(len(nba_players)))
pd.DataFrame(nba_players)

Number of players fetched: 4900

           id            full_name first_name     last_name  is_active
0       76001       Alaa Abdelnaby       Alaa     Abdelnaby      False
1       76002      Zaid Abdul-Aziz       Zaid    Abdul-Aziz      False
2       76003  Kareem Abdul-Jabbar     Kareem  Abdul-Jabbar      False
3          51   Mahmoud Abdul-Rauf    Mahmoud    Abdul-Rauf      False
4        1505    Tariq Abdul-Wahad      Tariq   Abdul-Wahad      False
...       ...                  ...        ...           ...        ...
4895  1627790           Ante Zizic       Ante         Zizic      False
4896    78647             Jim Zoet        Jim          Zoet      False
4897    78648            Bill Zopf       Bill          Zopf      False
4898  1627826          Ivica Zubac      Ivica         Zubac       True
4899    78650           Matt Zunic       Matt         Zunic      False

[4900 rows x 5 columns]

In [10]:
from nba_api.stats.static import teams

# get_teams returns a list of 30 dictionaries, each an NBA team.
nba_teams = teams.get_teams()
print("Number of teams fetched: {}".format(len(nba_teams)))
pd.DataFrame(nba_teams)

Number of teams fetched: 30

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Georgia,1949
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966
5,1610612742,Dallas Mavericks,DAL,Mavericks,Dallas,Texas,1980
6,1610612743,Denver Nuggets,DEN,Nuggets,Denver,Colorado,1976
7,1610612744,Golden State Warriors,GSW,Warriors,Golden State,California,1946
8,1610612745,Houston Rockets,HOU,Rockets,Houston,Texas,1967
9,1610612746,Los Angeles Clippers,LAC,Clippers,Los Angeles,California,1970
10,1610612747,Los Angeles Lakers,LAL,Lakers,Los Angeles,California,1948
11,1610612748,Miami Heat,MIA,Heat,Miami,Florida,1988
12,1610612749,Milwaukee Bucks,MIL,Bucks,Milwaukee,Wisconsin,1968
13,1610612750,Minnesota Timberwolves,MIN,Timberwolves,Minnesota,Minnesota,1989
14,1610612751,Brooklyn Nets,BKN,Nets,Brooklyn,New York,1976
15,1610612752,New York Knicks,NYK,Knicks,New York,New York,1946
16,1610612753,Orlando Magic,ORL,Magic,Orlando,Florida,1989
17,1610612754,Indiana Pacers,IND,Pacers,Indiana,Indiana,1976
18,1610612755,Philadelphia 76ers,PHI,76ers,Philadelphia,Pennsylvania,1949
19,1610612756,Phoenix Suns,PHX,Suns,Phoenix,Arizona,1968
20,1610612757,Portland Trail Blazers,POR,Trail Blazers,Portland,Oregon,1970
21,1610612758,Sacramento Kings,SAC,Kings,Sacramento,California,1948
22,1610612759,San Antonio Spurs,SAS,Spurs,San Antonio,Texas,1976
23,1610612760,Oklahoma City Thunder,OKC,Thunder,Oklahoma City,Oklahoma,1967
24,1610612761,Toronto Raptors,TOR,Raptors,Toronto,Ontario,1995
25,1610612762,Utah Jazz,UTA,Jazz,Utah,Utah,1974
26,1610612763,Memphis Grizzlies,MEM,Grizzlies,Memphis,Tennessee,1995
27,1610612764,Washington Wizards,WAS,Wizards,Washington,District of Columbia,1961
28,1610612765,Detroit Pistons,DET,Pistons,Detroit,Michigan,1948
29,1610612766,Charlotte Hornets,CHA,Hornets,Charlotte,North Carolina,1988

In [15]:
spurs = [team for team in nba_teams if team["abbreviation"] == "LAL"][0]
spurs

{'id': 1610612747,
 'full_name': 'Los Angeles Lakers',
 'abbreviation': 'LAL',
 'nickname': 'Lakers',
 'city': 'Los Angeles',
 'state': 'California',
 'year_founded': 1948}

In [17]:
big_fundamental = [
    player for player in nba_players if player["first_name"] == "LeBron"
][0]
big_fundamental

{'id': 2544,
 'full_name': 'LeBron James',
 'first_name': 'LeBron',
 'last_name': 'James',
 'is_active': True}

In [33]:
from nba_api.stats.endpoints import playerprofilev2

player = playerprofilev2.PlayerProfileV2(player_id='2544')

pd.DataFrame(player.get_normalized_dict()['CareerHighs'])
# dict_keys(['resource', 'parameters', 'resultSets'])

,PLAYER_ID,GAME_ID,GAME_DATE,VS_TEAM_ID,VS_TEAM_CITY,VS_TEAM_NAME,VS_TEAM_ABBREVIATION,STAT,STAT_VALUE,STAT_ORDER,DATE_EST
0,2544,0021300893,MAR 03 2014,1610612766,Charlotte,Bobcats,CHA,PTS,61,1,2014-03-03T00:00:00
1,2544,0022300650,JAN 27 2024,1610612744,Golden State,Warriors,GSW,REB,20,2,2024-01-27T00:00:00
2,2544,0021201009,MAR 20 2013,1610612739,Cleveland,Cavaliers,CLE,OREB,7,3,2013-03-20T00:00:00
3,2544,0021100547,MAR 04 2012,1610612747,Los Angeles,Lakers,LAL,OREB,7,3,2012-03-04T00:00:00
4,2544,0022300650,JAN 27 2024,1610612744,Golden State,Warriors,GSW,DREB,19,4,2024-01-27T00:00:00
5,2544,0021900613,JAN 15 2020,1610612753,Orlando,Magic,ORL,AST,19,5,2020-01-15T00:00:00
6,2544,0021700819,FEB 09 2018,1610612737,Atlanta,Hawks,ATL,AST,19,5,2018-02-09T00:00:00
7,2544,0020400303,DEC 13 2004,1610612763,Memphis,Grizzlies,MEM,STL,7,6,2004-12-13T00:00:00
8,2544,0020300967,MAR 16 2004,1610612741,Chicago,Bulls,CHI,BLK,5,7,2004-03-16T00:00:00
9,2544,0020300812,FEB 23 2004,1610612740,New Orleans,Hornets,NOH,BLK,5,7,2004-02-23T00:00:00
10,2544,0021700122,NOV 03 2017,1610612764,Washington,Wizards,WAS,FGM,23,8,2017-11-03T00:00:00
11,2544,0020400977,MAR 20 2005,1610612761,Toronto,Raptors,TOR,FGA,36,9,2005-03-20T00:00:00
12,2544,0022200719,JAN 24 2023,1610612746,LA,Clippers,LAC,FG3M,9,10,2023-01-24T00:00:00
13,2544,0022201228,APR 09 2023,1610612762,Utah,Jazz,UTA,FG3A,14,11,2023-04-09T00:00:00
14,2544,0022200719,JAN 24 2023,1610612746,LA,Clippers,LAC,FG3A,14,11,2023-01-24T00:00:00
15,2544,0022100520,DEC 29 2021,1610612763,Memphis,Grizzlies,MEM,FG3A,14,11,2021-12-29T00:00:00
16,2544,0020500929,MAR 12 2006,1610612748,Miami,Heat,MIA,FTM,24,12,2006-03-12T00:00:00
17,2544,0020500929,MAR 12 2006,1610612748,Miami,Heat,MIA,FTA,28,13,2006-03-12T00:00:00

In [16]:
from nba_api.stats.endpoints import playercareerstats

career = playercareerstats.PlayerCareerStats(player_id='2544')

career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,2544,2003-04,00,1610612739,CLE,19.0,79,79,3120.0,622,...,0.754,99,333,432,465,130,58,273,149,1654
1,2544,2004-05,00,1610612739,CLE,20.0,80,80,3388.0,795,...,0.750,111,477,588,577,177,52,262,146,2175
2,2544,2005-06,00,1610612739,CLE,21.0,79,79,3361.0,875,...,0.738,75,481,556,521,123,66,260,181,2478
3,2544,2006-07,00,1610612739,CLE,22.0,78,78,3190.0,772,...,0.698,83,443,526,470,125,55,250,171,2132
4,2544,2007-08,00,1610612739,CLE,23.0,75,74,3027.0,794,...,0.712,133,459,592,539,138,81,255,165,2250
5,2544,2008-09,00,1610612739,CLE,24.0,81,81,3054.0,789,...,0.780,106,507,613,587,137,93,241,139,2304
6,2544,2009-10,00,1610612739,CLE,25.0,76,76,2966.0,768,...,0.767,71,483,554,651,125,77,261,119,2258
7,2544,2010-11,00,1610612748,MIA,26.0,79,79,3063.0,758,...,0.759,80,510,590,554,124,50,284,163,2111
8,2544,2011-12,00,1610612748,MIA,27.0,62,62,2326.0,621,...,0.771,94,398,492,387,115,50,213,96,1683
9,2544,2012-13,00,1610612748,MIA,28.0,76,76,2877.0,765,...,0.753,97,513,610,551,129,67,226,110,2036
10,2544,2013-14,00,1610612748,MIA,29.0,77,77,2902.0,767,...,0.750,81,452,533,488,121,26,270,126,2089
11,2544,2014-15,00,1610612739,CLE,30.0,69,69,2493.0,624,...,0.710,51,365,416,511,109,49,272,135,1743
12,2544,2015-16,00,1610612739,CLE,31.0,76,76,2709.0,737,...,0.731,111,454,565,514,104,49,249,143,1920
13,2544,2016-17,00,1610612739,CLE,32.0,74,74,2795.0,736,...,0.674,97,542,639,646,92,44,303,134,1954
14,2544,2017-18,00,1610612739,CLE,33.0,82,82,3026.0,857,...,0.731,97,612,709,747,116,71,347,136,2251
15,2544,2018-19,00,1610612747,LAL,34.0,55,55,1937.0,558,...,0.665,57,408,465,454,72,33,197,94,1505
16,2544,2019-20,00,1610612747,LAL,35.0,67,67,2316.0,643,...,0.693,66,459,525,684,78,36,261,118,1698
17,2544,2020-21,00,1610612747,LAL,36.0,45,45,1504.0,422,...,0.698,29,317,346,350,48,25,168,70,1126
18,2544,2021-22,00,1610612747,LAL,37.0,56,56,2084.0,640,...,0.756,63,396,459,349,73,59,196,121,1695
19,2544,2022-23,00,1610612747,LAL,38.0,55,54,1954.0,609,...,0.768,65,392,457,375,50,32,178,88,1590
20,2544,2023-24,00,1610612747,LAL,39.0,55,55,1926.0,525,...,0.732,47,343,390,435,70,33,177,65,1384

In [35]:
from nba_api.stats.endpoints import alltimeleadersgrids

alltimeleadersgrids = alltimeleadersgrids.AllTimeLeadersGrids()

alltimeleadersgrids.get_data_frames()[0]
# dict_keys(['GPLeaders', 'PTSLeaders', 'ASTLeaders', 'STLLeaders', 'OREBLeaders', 'DREBLeaders', 'REBLeaders', 'BLKLeaders', 'FGMLeaders', 'FGALeaders', 'FG_PCTLeaders', 'TOVLeaders', 'FG3MLeaders', 'FG3ALeaders', 'FG3_PCTLeaders', 'PFLeaders', 'FTMLeaders', 'FTALeaders', 'FT_PCTLeaders'])

   PLAYER_ID          PLAYER_NAME    GP  GP_RANK IS_ACTIVE_FLAG
0        305        Robert Parish  1611        1              N
1      76003  Kareem Abdul-Jabbar  1560        2              N
2       1713         Vince Carter  1541        3              N
3       1717        Dirk Nowitzki  1522        4              N
4        304        John Stockton  1504        5              N
5       2544         LeBron James  1476        6              Y
6        252          Karl Malone  1476        6              N
7        708        Kevin Garnett  1462        8              N
8        788         Kevin Willis  1424        9              N
9       1891          Jason Terry  1410       10              N

In [36]:
alltimeleadersgrids.get_data_frames()[1]

   PLAYER_ID          PLAYER_NAME    PTS  PTS_RANK IS_ACTIVE_FLAG
0       2544         LeBron James  40036         1              Y
1      76003  Kareem Abdul-Jabbar  38387         2              N
2        252          Karl Malone  36928         3              N
3        977          Kobe Bryant  33643         4              N
4        893       Michael Jordan  32292         5              N
5       1717        Dirk Nowitzki  31560         6              N
6      76375     Wilt Chamberlain  31419         7              N
7        406     Shaquille O'Neal  28596         8              N
8     201142         Kevin Durant  28427         9              Y
9       2546      Carmelo Anthony  28289        10              N